"""initial migration

Revision ID: d8f0cd451a4a
Revises: 
Create Date: 2020-04-04 12:47:29.734382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8f0cd451a4a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('address', sa.String(length=128), nullable=True),
    sa.Column('ph_number', sa.Text(), nullable=True),
    sa.Column('length_shirt', sa.Text(), nullable=True),
    sa.Column('chest_shirt', sa.Text(), nullable=True),
    sa.Column('waist_shirt', sa.Text(), nullable=True),
    sa.Column('shoulder_shirt', sa.Text(), nullable=True),
    sa.Column('hips_shirt', sa.Text(), nullable=True),
    sa.Column('neck_shirt', sa.Text(), nullable=True),
    sa.Column('sleeves_shirt', sa.Text(), nullable=True),
    sa.Column('flair_shirt', sa.Text(), nullable=True),
    sa.Column('slit_shirt', sa.Text(), nullable=True),
    sa.Column('armhole_shirt', sa.Text(), nullable=True),
    sa.Column('biceps_shirt', sa.Text(), nullable=True),
    sa.Column('front_shirt', sa.Text(), nullable=True),
    sa.Column('back_shirt', sa.Text(), nullable=True),
    sa.Column('length_trouser', sa.Text(), nullable=True),
    sa.Column('poncha_trouser', sa.Text(), nullable=True),
    sa.Column('length_blouse', sa.Text(), nullable=True),
    sa.Column('chest_blouse', sa.Text(), nullable=True),
    sa.Column('shoulder_blouse', sa.Text(), nullable=True),
    sa.Column('neck_blouse', sa.Text(), nullable=True),
    sa.Column('sleeves_blouse', sa.Text(), nullable=True),
    sa.Column('armhole_blouse', sa.Text(), nullable=True),
    sa.Column('biceps_blouse', sa.Text(), nullable=True),
    sa.Column('plate_blouse', sa.Text(), nullable=True),
    sa.Column('extra_1', sa.Text(), nullable=True),
    sa.Column('extra_2', sa.Text(), nullable=True),
    sa.Column('extra_3', sa.Text(), nullable=True),
    sa.Column('extra_4', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('customers')
    # ### end Alembic commands ###
